[package]
name = "evo_domain"
version = "0.1.0"
authors = ["Franz Amador <franzamador@gmail.com>"]
edition = "2018"

[dependencies]
evo_domain_derive = { path = "evo_domain_derive" }
rand = "0.7"
rand_distr = "0.2"
rand_pcg = "0.2"
smallvec = "1.4"
