[package]
name = "evo_main"
version = "0.1.0"
authors = ["Franz Amador <franzamador@gmail.com>"]
edition = "2018"

[dependencies]
evo_glium = { path = "../evo_glium" }
evo_model = { path = "../evo_domain" }
log = { version = "0.4" }
simple_logger = "1.4.0"
