[package]
name = "evo_main"
version = "0.1.0"
authors = ["Franz Amador <franzamador@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.33"
evo_domain = { path = "../evo_domain" }
evo_glium = { path = "../evo_glium" }
