[package]
name = "evo_model"
version = "0.1.0"
authors = ["Franz Amador <franzamador@gmail.com>"]

[dependencies]
evo_model_derive = { path = "evo_model_derive" }
evo_view_model = { path = "../evo_view_model" }
