[package]
name = "evo_model"
version = "0.1.0"
authors = ["Franz Amador <franzamador@gmail.com>"]
edition = "2018"

[dependencies]
evo_model_derive = { path = "evo_model_derive" }
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
rand = "0.7"
rand_pcg = "0.2"
